---
- name: Stop and remove httpd
  hosts: all
  become: yes
  tasks:
    - name: Stop httpd service
      ansible.builtin.systemd:
        name: httpd
        state: stopped 

    - name: Remove the service package
      ansible.builtin.dnf:
        name: httpd
        state: absent
